# Generated by Django 4.2 on 2023-11-01 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Games", "0002_gamesstory_delete_missing_truth_story"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Missing_truth_story",
        ),
        migrations.RemoveField(
            model_name="user_game_details",
            name="next_level",
        ),
    ]
