# Generated by Django 4.2 on 2023-10-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamesStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_no", models.IntegerField()),
                ("sub_level_no", models.IntegerField()),
                ("scene_name", models.TextField()),
                ("prompt", models.TextField()),
                ("Expected_answer", models.TextField()),
                ("points", models.IntegerField()),
                ("hint_text", models.TextField()),
                ("hint_link", models.TextField()),
                (
                    "gameID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Games.games_data",
                    ),
                ),
            ],
        ),
        
    ]
